apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-front-deployment
spec:
  selector:
   matchLabels:
    app: angular-front
  replicas: 1
  template:
    metadata:
      labels:
        app: angular-front
    spec:
      containers:
        - name: kangular
          image: diegoperedo/prueba:primerpush
          ports:
            - containerPort: 81
              name: angularport